[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_vault = "4jUN6DKrJSn9QGorzcX5xnQf9irrj5aC5sX4FjoqqPWo" # anchor-vault program id, used to deploy -> on localnet is created automatically

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet" # cluster where the program will be deployed
wallet = "~/.config/solana/id.json" # path to the wallet file

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts" # script commands for testing
