[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
farmlink_capstone = "3XXXV3XAM64BzAMa46YYYGVYmaYocjvY9q6vSHspASRF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/victorcarvalho/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
