[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_marketplace = "8tooD7yeL5tYeWWsz3pegP9din78nrqgkrQPC5wq3cag"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/victorcarvalho/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
