[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_amm = "4yi1JvRGv6ETmpkDsiC2tby35gVtBf2Hq3zkmKNwGLxx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/victorcarvalho/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
